version: "2.1"
services:

  namenode:
    image: bde2020/hadoop-namenode
    container_name: namenode
    hostname: namenode
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    networks:
      - csp-ce-net
    env_file:
      - ./hadoop-hive.env
    ports:
      - "50070:50070"
      - "8020:8020"


  datanode1:
    image: bde2020/hadoop-datanode
    container_name: datanode1
    hostname: datanode1
    volumes:
      - datanode1:/hadoop/dfs/data
    depends_on:
      - namenode
    env_file:
      - ./hadoop-hive.env
    networks:
      - csp-ce-net
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    ports:
      - "50075:50075"

  datanode2:
    image: bde2020/hadoop-datanode
    container_name: datanode2
    hostname: datanode2
    volumes:
      - datanode2:/hadoop/dfs/data
    depends_on:
      - namenode
    env_file:
      - ./hadoop-hive.env
    networks:
      - csp-ce-net
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    ports:
      - "50076:50075"

  datanode3:
    image: bde2020/hadoop-datanode
    container_name: datanode3
    hostname: datanode3
    volumes:
      - datanode3:/hadoop/dfs/data
    depends_on:
      - namenode
    env_file:
      - ./hadoop-hive.env
    networks:
      - csp-ce-net
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    ports:
      - "50077:50075"



networks:
  csp-ce-net:
    driver: bridge

volumes:
  db_data: {}
  namenode: {}
  datanode1: {}
  datanode2: {}
  datanode3: {}
